os:
  - windows
  - osx
  - linux

matrix:
  allow_failures:
    - os: windows

before_install:
  - openssl aes-256-cbc -K $encrypted_3fdf79acf4ff_key -iv $encrypted_3fdf79acf4ff_iv
    -in secret.gpg.enc -out secret.gpg
    -d
  - chmod +x gradlew

script: ./gradlew check

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
    - "$HOME/.konan/cache/"

deploy:
  provider: script
  script: ./gradlew publish
  skip_cleanup: true
  on:
    tags: true
    branch: master


